name: "Terraform"

on:
  pull_request:
    branches:
      - main

jobs:
  infrastructure_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.15.5"

      - name: Setup Google Cloud
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ vars.GOOGLE_PROJECT }}
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Terraform Plan
        run: |
          cd infra
          terraform init -backend-config="bucket=${{ vars.BUCKET_NAME }}"
          terraform plan -var="project_id=${{ vars.GOOGLE_PROJECT }}"
